apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: mock-server
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: postgres-primary
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: postgres-replica
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: postgres-keycloak
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: redis-master
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: redis-replica
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: haproxy-postgres
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
