namespace: methodology

k8s_secrets:
  db_primary_password: "change_me_primary"
  db_replica_password: "change_me_replica"
  db_keycloak_user: "keycloak_user"
  db_keycloak_password: "change_me_keycloak"
  master_encryption_key: "change_me_master_key_32_bytes_min"
  jwt_secret_key: "change_me_jwt_secret_32_bytes_min"
  keycloak_admin_user: "admin"
  keycloak_admin_password: "change_me_admin_password"
  keycloak_client_secret: "change_me_client_secret"
  redis_password: "change_me_redis_password"

kustomize_overlay: "{{ playbook_dir }}/../../deploy/k3s/overlays/real"
