---
- name: Fetch kubeconfig from first server
  hosts: k3s_servers
  become: true
  tasks:
    - name: Read kubeconfig
      ansible.builtin.slurp:
        path: /etc/rancher/k3s/k3s.yaml
      register: raw_kubeconfig

    - name: Save kubeconfig local
      ansible.builtin.copy:
        content: "{{ raw_kubeconfig.content | b64decode | regex_replace('127.0.0.1', ansible_host) }}"
        dest: "{{ playbook_dir }}/../../deploy/k3s/kubeconfig"
        mode: "0600"
      delegate_to: localhost
      become: false
      run_once: true
