apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: methodology
resources:
  - namespace.yaml
  - configmap-haproxy.yaml
  - postgres-primary.yaml
  - postgres-replica.yaml
  - postgres-keycloak.yaml
  - redis-master.yaml
  - redis-replica.yaml
  - keycloak.yaml
  - backend.yaml
  - frontend.yaml
  - mock-server.yaml
  - haproxy-postgres.yaml
